version: '3.1'

services:    
  db:
    build: ../../../images/WP2/db/
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: apiamt
      MYSQL_USER: apiamt
      MYSQL_PASSWORD: apiamt
      MYSQL_ROOT_PASSWORD: root
  
  spring:
    build: ../../../images/WP2/spring
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    links:
      - db