version: '3.1'

services:    
  db:
    build: ../../images/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: stackoveramt
      MYSQL_USER: stackoveramt
      MYSQL_PASSWORD: stackoveramt
      MYSQL_ROOT_PASSWORD: root
        
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    environment:
     - PMA_HOST=db
    restart: always
    ports:
     - 8888:80
     
  payara:
    build: ../../images/payara
    environment:
     - ADMIN_PASSWORD=adminadmin
    ports:
     - "8080:8080"
     - "4848:4848"
    links:
     - db:db 